// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.expo/**',
      '**/build/**',
      '**/coverage/**',
      'supabase/functions/**', // Deno runtime — linted separately by `deno lint`
      '**/next-env.d.ts', // generated by Next on every build
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // Metro's config is loaded by Node as CommonJS before any bundler runs.
    files: ['**/metro.config.js', '**/babel.config.js', '**/*.cjs'],
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'writable',
        __dirname: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    // PRD §14: structured logs without payment-card or unnecessary personal data. Guard the
    // obvious footgun — a raw voucher token or card field reaching a log line.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.object.name='console'] > Identifier[name=/^(token|cardNumber|cvc|pan|serviceRoleKey)$/]",
          message: 'Never log secrets, tokens or card data (PRD §14).',
        },
      ],
    },
  },
);
